spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world
    username: root
    password: adminpassword
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true